---

- src: https://github.com/superlumic/ansible-role-homebrew.git
  name: edward.superlumic-homebrew

- src: https://github.com/superlumic/ansible-role-osx-defaults.git
  name: edward.superlumic-osx-defaults

- src: https://github.com/superlumic/ansible-role-computername.git
  name: edward.superlumic-computername

- src: https://github.com/superlumic/ansible-role-cli.git
  name: edward.superlumic-cli

- src: https://github.com/superlumic/ansible-role-mysql.git
  name: edward.superlumic-mysql

- src: https://github.com/superlumic/ansible-role-php.git
  name: edward.superlumic-php

- src: https://github.com/superlumic/ansible-role-sublimetext.git
  name: edward.superlumic-sublimetext

- src: https://github.com/superlumic/ansible-role-node.git
  name: edward.superlumic-node

- src: https://github.com/superlumic/ansible-role-postgresql.git
  name: edward.superlumic-postgresql

- src: https://github.com/superlumic/ansible-role-vim.git
  name: edward.superlumic-vim

- src: https://github.com/superlumic/ansible-role-modjk.git
  name: edward.superlumic-modjk

- src: https://github.com/superlumic/ansible-role-skylab.git
  name: edward.superlumic-skylab
