---
galaxy_info:
  author: Edward Knowles
  description: Ansible profile role for all users
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
dependencies:
  - edward.superlumic-computername
  - edward.superlumic-cli
